In [2]:
import numpy as np

In [4]:
arr1=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr1,3)
print(newarr)
newarr1=np.array_split(arr1,4)
print(newarr1[1])

[array([1, 2]), array([3, 4]), array([5, 6])]
[3 4]


In [5]:
arr1=np.array([1,2,3,4,5,6])
newarr1=np.array_split(arr1,3)
print(newarr1[0])
print(newarr1[1])
print(newarr1[2])

[1 2]
[3 4]
[5 6]


In [8]:
arr1=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr1=np.array_split(arr1,3)

print(newarr1)



[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [9]:

arr1=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr1=np.array_split(arr1,3)

print(newarr1)
newarr1=np.array_split(arr1,3,axis=1)

print(newarr1)


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int32)]


In [15]:
arr=np.array([1,5,3,4,5,5,4])
x=np.where(arr == 5)
print(x)
x=np.where(arr%2==0)
print(x)
x=np.where(arr==0)
print(x)

(array([1, 4, 5], dtype=int64),)
(array([3, 6], dtype=int64),)
(array([], dtype=int64),)


In [35]:
arr1=np.array([5,8,6,12])
print(np.sort(arr1))

arr1[::-1].sort()
print(arr1)

print(np.sort(arr1[::-1]))
print()

arr1=np.array([[3,2,4],[5,0,1]])
print(np.sort(arr1))

[ 5  6  8 12]
[12  8  6  5]
[ 5  6  8 12]

[[2 3 4]
 [0 1 5]]


In [39]:
arr=np.array([True,False,True])
print(np.sort(arr))
arr=np.array(['banana','cherry','apple','blueberry'])
print(arr)

[False  True  True]
['banana' 'cherry' 'apple' 'blueberry']


In [47]:

x1=np.arange(9.0).reshape((3,3))
print(x1)
x2=np.arange(3.0)
np.add(x1,x2)


[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


array([[ 0.,  2.,  4.],
       [ 3.,  5.,  7.],
       [ 6.,  8., 10.]])

In [51]:
x1=np.arange(9.0).reshape((3,3))

x2=np.arange(3.0)
x1+x2

array([[ 0.,  2.,  4.],
       [ 3.,  5.,  7.],
       [ 6.,  8., 10.]])