In [4]:
import numpy as np
d=np.empty(2)
print(d)

[-1.81720762e+057  1.83161365e-238]


In [18]:
import numpy as np
e=np.empty(2)
print(e)

[1.81720762e+057 1.83161365e-238]


In [7]:
a=np.random.randn(2,3,4)
print(a)

[[[-1.72083179 -1.83488746 -0.89246158  0.43049733]
  [ 0.00964108 -1.82442195  0.53631267  0.59954361]
  [-1.99586587 -1.70246493  1.5641695   0.1103234 ]]

 [[ 0.83308442  1.64966425 -0.38440608  1.02263257]
  [-0.37849912 -0.55609997  1.47085113 -0.35170383]
  [-1.88530016  1.40331851 -1.36709661  0.6381692 ]]]


In [15]:
a=np.random.rand(3,3,4)
print(a)

[[[0.38088332 0.7245575  0.16892861 0.23715828]
  [0.3876577  0.51804243 0.11213802 0.11004499]
  [0.72291303 0.2915532  0.59062164 0.79284705]]

 [[0.86230476 0.52719594 0.67104616 0.68094668]
  [0.6153713  0.75311102 0.69647475 0.14497437]
  [0.55251443 0.53981017 0.02934872 0.06654368]]

 [[0.06495873 0.56488246 0.61317615 0.97178973]
  [0.85291476 0.45591793 0.8813082  0.98581353]
  [0.30772325 0.54994151 0.59990071 0.49556191]]]


In [17]:
a=np.random.randint((3,3,4))
print(a)

[0 2 1]


In [19]:
d=np.empty(3)
print(d)

[1.5e-323 1.5e-323 2.0e-323]


In [ ]:
# Function

In [26]:
d=np.logspace(2.0,3.0,base=11)
print(d)

[ 121.          127.06861089  133.44158573  140.13418954  147.16245292
  154.54321048  162.29414114  170.4338105   178.98171528  187.95833005
  197.38515624  207.28477367  217.68089462  228.59842063  240.06350216
  252.1036012   264.74755707  278.02565548  291.96970111  306.61309374
  321.99090828  338.1399788   355.09898672  372.90855348  391.61133786
  411.25213811  431.8779993   453.53832599  476.28500058  500.17250753
  525.25806395  551.60175658  579.26668573  608.31911646  638.82863725
  670.86832671  704.51492865  739.84903583  776.95528307  815.92254996
  856.8441737   899.81817275  944.94748153  992.34019705 1042.10983778
 1094.37561556 1149.26272117 1206.9026242  1267.43338792 1331.        ]


In [24]:
d=np.logspace(2.0,3.0,num=5)
print(d)

[ 100.          177.827941    316.22776602  562.34132519 1000.        ]


In [25]:
d=np.logspace(3.0,4.0,num=5)
print(d)

[ 1000.          1778.27941004  3162.27766017  5623.4132519
 10000.        ]


In [27]:
d=np.logspace(2.0,3.0,base=2)
print(d)

[4.         4.05698555 4.11478293 4.17340372 4.23285965 4.2931626
 4.35432466 4.41635805 4.4792752  4.54308869 4.60781129 4.67345595
 4.74003581 4.8075642  4.87605462 4.94552078 5.01597658 5.08743612
 5.15991371 5.23342383 5.30798122 5.38360077 5.46029763 5.53808714
 5.61698488 5.69700662 5.77816838 5.8604864  5.94397716 6.02865736
 6.11454394 6.2016541  6.29000526 6.37961511 6.47050158 6.56268285
 6.65617737 6.75100385 6.84718126 6.94472885 7.04366615 7.14401294
 7.24578931 7.34901563 7.45371255 7.55990103 7.6676023  7.77683793
 7.88762977 8.        ]


In [30]:
d=np.logspace(2.0,4.0,num=3,base=2)
print(d)

[ 4.  8. 16.]


In [ ]:
# bsae 2 hai 2 do aa gyi aab tisri ke liye 2 aur 4 ke bich 3 to 2 ka power 3 to 8 aa gyi

In [35]:
d = np.logspace(2.0, 3.0, num=8, dtype=int)
print(d)

[ 100  138  193  268  372  517  719 1000]


In [36]:
d = np.logspace(2.0, 3.0, num=8, dtype=float)
print(d)

[ 100.          138.94954944  193.06977289  268.26957953  372.75937203
  517.94746792  719.685673   1000.        ]


In [37]:
e=np.arange(4)
print(e)

[0 1 2 3]


In [38]:
e=np.arange(15)
print(e)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [39]:
e=np.arange(2,10)
print(e)

[2 3 4 5 6 7 8 9]


In [40]:
e=np.arange(3,32,3)
print(e)

[ 3  6  9 12 15 18 21 24 27 30]
