In [1]:
import numpy as np


In [ ]:
# Arithmatic operation

In [5]:
e=np.arange(0,5)
print(e)

[0 1 2 3 4]


In [6]:
b=np.arange(1,6)
c=e+b
print(c)

[1 3 5 7 9]


In [7]:
b=np.arange(1,7)
c=e+b
print(c)

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [8]:
b=np.arange(1,6)
c=e-b
print(c)

[-1 -1 -1 -1 -1]


In [11]:
b=np.arange(2,7)
c=e/b
print(c)

[0.         0.33333333 0.5        0.6        0.66666667]


In [12]:
b=np.arange(3,8)
c=b/e
print(c)

[ inf 4.   2.5  2.   1.75]


C:\Users\ALWAYSRAMESH\AppData\Local\Temp\ipykernel_20732\2691869702.py:2: RuntimeWarning: divide by zero encountered in divide
  c=b/e


In [14]:
b=np.arange(1,6)
c=e-100
print(c)

[-100  -99  -98  -97  -96]


In [ ]:
# scalar array means fix value

In [18]:

c=1/e
print(c)

[       inf 1.         0.5        0.33333333 0.25      ]


C:\Users\ALWAYSRAMESH\AppData\Local\Temp\ipykernel_20732\1653523989.py:1: RuntimeWarning: divide by zero encountered in divide
  c=1/e


In [17]:

c=e**2
print(c)

[ 0  1  4  9 16]


In [ ]:
# sqrt function e=2.78  https://docs.scipy.org/doc/numpy-1.10.0/reference/ufuncs.html   1,4,8

In [19]:
np.sqrt(e)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [20]:
np.max(e)

4

In [21]:
np.exp(e)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [23]:
e.max()

4

In [24]:
np.max(e)

4

In [28]:
a=np.arange(2,10)
print(a)
c=np.sqrt(a)
print(c)

[2 3 4 5 6 7 8 9]
[1.41421356 1.73205081 2.         2.23606798 2.44948974 2.64575131
 2.82842712 3.        ]


In [29]:
d=np.exp(a)
print(d)

[7.38905610e+00 2.00855369e+01 5.45981500e+01 1.48413159e+02
 4.03428793e+02 1.09663316e+03 2.98095799e+03 8.10308393e+03]


In [59]:
arr=np.array([1,2,3,4],dtype='i8')    
print(arr)

[1 2 3 4]


In [60]:
print(arr.dtype)

int64


In [51]:
arr=np.array([1,2,3,4],dtype='i2')
print(arr)

[1 2 3 4]


In [ ]:
# how to convert one data type to another datatype

In [61]:
arr=np.arr([1.1,2.2,3.3])
print(arr.)

AttributeError: module 'numpy' has no attribute 'arr'

In [62]:
arr2=arr.astype("i")
print(arr2.dtype)

int32
