In [1]:
# reshape = we can change in any dimension

In [2]:
import numpy as np

In [3]:
a = np.array([[2,3,4],[3,4,5]])

In [4]:
print(a)
print(a.ndim)
print(a.shape)

[[2 3 4]
 [3 4 5]]
2
(2, 3)


In [5]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[2 3]
 [4 3]
 [4 5]]
(3, 2)


In [6]:
c = np.arange(0,24)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [8]:
print(c.reshape(4,3,2))

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [9]:
c = np.random.randint(1,20,(4,3,2))
print(c)

[[[ 4  5]
  [ 7 12]
  [ 2  8]]

 [[17 16]
  [15 17]
  [ 9 12]]

 [[ 8  1]
  [ 2  3]
  [ 2  4]]

 [[15  3]
  [ 3 19]
  [ 8 14]]]


In [12]:
d = np.array([1,2,3])
print(d.itemsize)

4


In [1]:
# 8 means har ek element ko store karne ke liye 64 

In [4]:
import numpy as np


In [5]:
d = np.array([1,2,3])
print(d.itemsize)
print(d.size)
print(d.nbytes)

4
3
12


In [6]:
x = np.array([1,2,3,4,5],dtype = np.int8)
print(x.itemsize)
print(x.size)
print(x.nbytes)

1
5
5


In [7]:
x = np.array([1,2,3,4,5],dtype = np.float32)
print(x.itemsize)
print(x.size)
print(x.nbytes)

4
5
20
