In [1]:
# flatten() function - convert a multi-dimensional array into a one-dimensional array

In [2]:
import numpy as np

In [3]:
a = np.array([[1,4,7],[2,5,8],[3,6,9]])

In [4]:
b = a.flatten()
print(b)

[1 4 7 2 5 8 3 6 9]


In [5]:
b = a.flatten('F')
print(b)

[1 2 3 4 5 6 7 8 9]


In [6]:
# F likhne se column wise print hoga

In [7]:
# indexing and slicing


In [9]:
arr =np.array([1,2,3,4,5,6,7])

In [11]:
print(arr[::2])

[1 3 5 7]


In [12]:
print(arr[:2])

[1 2]


In [13]:
print(arr[2:])

[3 4 5 6 7]


In [14]:
print(arr[:5:3])

[1 4]


In [15]:
print(arr[4::4])

[5]


In [16]:
print(arr[1:1:1])

[]


In [17]:
print(arr[3])

4


In [18]:
print(arr[2:5])

[3 4 5]


In [19]:
print(arr[-3:-1])

[5 6]


In [20]:
print(arr[::-1])

[7 6 5 4 3 2 1]
