In [ ]:
import numpy as np

In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


In [ ]:
print(arr[0:2:2,1:4:2])

[[2 4]]


In [ ]:
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2:2,1:4:2])

[[2 4]]


In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
arr=np.array([[[1,2,3],[11,4,5]],[[6,7,8],[13,9,10]]])
print(arr[1,1,1])

9


In [ ]:
rr=np.array([[[1,2,3],[11,4,5]],[[6,7,8],[13,9,10]]])
print(arr[::1,1,1])

[4 9]


In [ ]:
print(arr[::,:1:1,1])

[[2]
 [7]]


In [ ]:
print(arr[::,::,1])

[[2 4]
 [7 9]]


In [ ]:
print(arr[::,::,::])

[[[ 1  2  3]
  [11  4  5]]

 [[ 6  7  8]
  [13  9 10]]]
