In [4]:
# advanced indexing

In [2]:
import numpy as np

In [3]:
x = np.array([[1,2],[3,4],[5,6]])
y = x[[0,1,2],[0,1,0]]
print(y)

[1 4 5]


In [5]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = a[[0,1,2],[0,1,2]]
print(b)

[1 5 9]


In [6]:
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(x)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [7]:
#slicing

In [9]:
z = x[1:4,1:3]
print('After slicing, our array becomes.')
print(x)

After slicing, our array becomes.
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [10]:
# using advanced index for column

In [12]:
y = x[1:4,[1,2]]
print('Slicing using advanced index for column.')
print(y)

Slicing using advanced index for column.
[[ 4  5]
 [ 7  8]
 [10 11]]


In [14]:
a = np.array([[1,2,7],[3,6,8],[23,4,7]])
print(a>5)
print(a[a>5])

[[False False  True]
 [False  True  True]
 [ True False  True]]
[ 7  6  8 23  7]


In [15]:
# Copy and View

In [16]:
arr = np.array([2,4,6,8,10])
nc = arr
nc[0] = 12
# Printing the values
print("Original array - ",arr)
print("Assigned array - ",nc)

Original array -  [12  4  6  8 10]
Assigned array -  [12  4  6  8 10]


In [17]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]
