In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [4]:
arr=np.array([1,8,3,3,5])
print('original Array:', arr)
arr=np.append(arr,[7])
print('Array after appending:',arr)

original Array: [1 8 3 3 5]
Array after appending: [1 8 3 3 5 7]


In [8]:
arr1=np.array([1,8,3,3,5])
arr2=np.array([1,2,3,4,5])
arr3=np.append(arr1,arr2)
print('Array After appending:', arr3)
print(arr1+arr2)

Array After appending: [1 8 3 3 5 1 2 3 4 5]
[ 2 10  6  7 10]


In [11]:
arr=np.array([1,2,3,4,5])
for x in arr:
    print(x)   # ek hi line ke l

1
2
3
4
5


In [35]:
arr=np.array([[1,2,3,4,5],[2,4,5,6,7]])
for x in np.nditer(arr[:,::2]):
    print(x) 

1
3
5
2
5
7


In [28]:
arr=np.array([[[1,2,3,4,5],[2,4,5,6,7],[4,6,8,3,6]]])
for x in arr:
    print("x represent the 2-D array:")
for y in x:
     print(y)   

x represent the 2-D array:
[1 2 3 4 5]
[2 4 5 6 7]
[4 6 8 3 6]


In [30]:
arr=np.array([[[[1,2,3,4,5],[2,4,5,6,7],[4,6,8,3,6],[3,5,6,7,8]]]])
for x in arr:
    
    print("x represent the 2-D array:")
for y in x:
    for z in y:
     print(z)

x represent the 2-D array:
[1 2 3 4 5]
[2 4 5 6 7]
[4 6 8 3 6]
[3 5 6 7 8]


In [32]:
arr=np.array([[[1,2],[3,4],[5,6],[7,8]]])
for x in np.nditer(arr):
    print(x)          # ek hi line me lane ke liye nditer kyuki esme ek hi loop me ho jata hai line by line

1
2
3
4
5
6
7
8


In [34]:
arr=np.array([[[1,2],[3,4],[5,6],[7,8]]])
for x in np.nditer(arr[:,::2]):
    print(x) 

1
2
5
6
