In [1]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4])
for idx, x in np.ndenumerate(arr):
   print(idx,x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4


In [4]:
arr=np.array([[1,2,3,4],[4,6,8,9]])
for idx, x in np.ndenumerate(arr):
   print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 4
(1, 1) 6
(1, 2) 8
(1, 3) 9


In [8]:
arr=np.array([[[1,2],[3,4],[4,6],[8,9]]])
for idx, x in np.ndenumerate(arr):
   print(idx,x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(0, 2, 0) 4
(0, 2, 1) 6
(0, 3, 0) 8
(0, 3, 1) 9


In [10]:
arr=np.array([[[1,2],[3,4]],[[4,6],[8,9]]])
for idx, x in np.ndenumerate(arr):
   print(idx,x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 4
(1, 0, 1) 6
(1, 1, 0) 8
(1, 1, 1) 9


In [13]:
arr=np.array([[[1,2],[3,4]],[[4,6],[8,9]]])

print(arr)

[[[1 2]
  [3 4]]

 [[4 6]
  [8 9]]]


In [27]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)

[1 2 3 4 5 6]


In [26]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [30]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.stack((arr1,arr2))
print(arr3)
arr=np.stack((arr1,arr2), axis=1)
print()
print(arr)       #stack= colomn wise karta hai

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


In [34]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr3=np.hstack((arr1,arr2))
arr4=np.vstack((arr1,arr2))
print(arr3)
print()
print(arr4)

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]


In [41]:
arr1=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr1,3)
print(newarr)
newarr1=np.array_split(arr1,4)
print(newarr1)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]
